### ISSUE TITLE
Unable to make or receive any call

### ISSUE THREAD

**Issue by YgrekIx** [milaq/android_device_lge_p940#9] opened 2013-04-12 14:15 UTC
Every one or two days phone block any incoming or outgoing call. Signal strength shows ok. Turning on/off aeroplane mode or switching between 2g/3g mode don't help. Only reboot helps.

I got logs from logcat if needed. If I can provide any other log's just tell me.

**Comment by milaq** [comment] 2013-04-12 14:17
duplicate of https://github.com/milaq/android_device_lge_p940/issues/2
ril recovery seems to be the problem

**Closed as completed** 2013-04-12 14:17 UTC
Labels: duplicate, invalid
